name: John Starr Dewar
markdown: redcarpet
pygments: true
url: http://jstarrdewar.com
title: John Starr Dewar
author: John Starr Dewar
permalink: /blog/:year/:month/:day/:title/
dart2js: ~/dart/dart-sdk/bin/dart2js
dart_src: _dart/web
dart_main: main.dart
picture:
  source: assets/images/_fullsize
  output: generated
  markup: "picturefill"
  presets:
    default:
      ppi: [1, 2]
      attr:
        class: "fullWidthImage"
        itemprop: "image"
      source_default:
        width: "712"